name:  Cabbie Continuous Integration

# Trigger on every master branch push and pull request
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    strategy:
      matrix:
        targetplatform: [x64]
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup go
      uses: actions/setup-go@v2

    - run: go build
